# Generated by Django 4.0.6 on 2022-09-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
