# Generated by Django 4.0.6 on 2022-09-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
