# Generated by Django 4.0.6 on 2022-09-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_account_referal_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
