# Generated by Django 4.0.6 on 2022-09-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
