# Generated by Django 4.0.6 on 2022-09-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, upload_to='banner')),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='static')),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=True, max_length=255)),
                ('productname', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('dicscount_price', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('image', models.FileField(default=True, upload_to='static')),
                ('is_active', models.IntegerField(default=1)),
                ('category_name', models.CharField(max_length=250, null=True)),
                ('image2', models.FileField(default=True, upload_to='static')),
                ('image3', models.FileField(default=True, upload_to='static')),
                ('stock', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('size', 'size')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=b'I01\n')),
                ('created_date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=255)),
                ('url_slug', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='static')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('categories_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=255)),
                ('media_content', models.FileField(upload_to='')),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategories'),
        ),
    ]
