# Generated by Django 4.0.6 on 2022-09-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories_id',
        ),
    ]
