# Generated by Django 4.0.6 on 2022-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_limit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
