# Generated by Django 4.0.6 on 2022-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_coupon_max_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_to', models.DateTimeField(null=True)),
                ('discount_amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
