# Generated by Django 4.0.6 on 2022-09-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_cat_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.categories'),
        ),
    ]
