# Generated by Django 4.0.6 on 2022-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_offer',
            name='offer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
