# Generated by Django 4.0.6 on 2022-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_product_offer_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer1',
            field=models.IntegerField(null=True),
        ),
    ]
