# Generated by Django 4.0.6 on 2022-09-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_product_product_offer1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_offer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
