# Generated by Django 4.0.6 on 2022-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_product_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_offer',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product_offer',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
